name: test suite

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.2', '8.3', '8.4', '8.5']
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, gd, mysql, xml
          ini-values: post_max_size=256M, max_execution_time=180
          tools: composer:v2

      - name: Create cache dir
        run: |
          mkdir -p .cache
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v5
        with:
          path: |
            path: ${{ steps.composer-cache.outputs.dir }}
            ~/.cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install

      - name: linter
        run: bin/linter.sh

      - name: phpcs
        run: bin/phpcs.sh
